### ISSUE TITLE
provide structured clone of state on functional updater function

### ISSUE THREAD

**Issue by shahriar-shojib** [poly-state/poly-state#10]
https://github.com/poly-state/poly-state/blob/4253480456adf0183f8e49ef44539dcf6d7a0898/src/store.class.ts#L74

**Comment by sonjoydatta** [comment]
Even though structuredClone() is not part of ECMAScript, it was added to the platform-specific parts of many platforms and is still widely available (either now or soon):

[Chrome 98](https://chromestatus.com/feature/5630001077551104)
[Safari 137 (Technology Preview Release)](https://developer.apple.com/safari/technology-preview/release-notes/)
[Firefox 94](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility)
[Node.js 17.0](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility)
[Deno 1.14](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility)

**Comment by shahriar-shojib** [comment]
Polyfills are available and most module bundlers will take care of it, or we can write our own function to deepClone an object

**Comment by sonjoydatta** [comment]
Yes, that would be great. Lemme write our own function 😅
