### ISSUE TITLE
isEqual not working for nested Arrays and Objects

### ISSUE THREAD

**Issue by sonjoydatta** [poly-state/poly-state#4]
For example,
`const a = [1, 2, [3, 4]];
const b = [1, 2, [3, 4]];`

`const a = {
	foo: 'bar',
	baz: {
		foo: 'bar',
	},
};
const b = {
	foo: 'bar',
	baz: {
		foo: 'bar',
	},
};`

**Comment by shahriar-shojib** [comment]
fixed in #2
